### ISSUE TITLE
[PREGUNTA] Presentación

### ISSUE THREAD

**Issue by delor34n** [emir-munoz/tesis-usach#1]
¿Existe alguna presentación (slides) en latex con el formato que pide la Universidad?

**Comment by emir-munoz** [comment]
De hecho tengo un template para hacer presentaciones en beamer que use para mi defensa. No sigue los formatos de la Universidad, sólo agregué el logo en ese momento. 
Supongo que el template de presentaciones ha cambiado con el tiempo....
Si quieres generar un template, algo que puedes tomar como modelo es esto https://github.com/igorbrigadir/insight-templates/tree/master/latex-presentation

**Comment by delor34n** [comment]
Vale! voy a ver que se puede hacer y lo subo!
